changed: update create-changelog workflow

diff --git a/.github/workflows/create-changelog.yml b/.github/workflows/create-changelog.yml
--- a/.github/workflows/create-changelog.yml
+++ b/.github/workflows/create-changelog.yml
@@ -24,15 +24,23 @@ jobs:
           fetch-depth: 0
 
       # Get the version from version.json file and store it in the output file
-      # - name: Get version from version.json
-      #   id: retrieve_version
-      #   run: |
-      #     new_version=$(jq -r '.version' version.json)
-      #     if [ -z "$new_version" ]; then
-      #       echo "Error: version field is empty or not found in version.json!"
-      #       exit 1
-      #     fi
-      #     echo "new_version=$new_version" >> "$GITHUB_OUTPUT"
+      - name: Get version from version.json
+        id: retrieve_version
+        run: |
+          new_version=$(jq -r '.version' version.json)
+          if [ -z "$new_version" ]; then
+            echo "Error: version field is empty or not found in version.json!"
+            exit 1
+          fi
+          echo "new_version=$new_version" >> "$GITHUB_OUTPUT"
+
+      # Set release version for changelog
+      - name: Set release version for changelog
+        run: |
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+          git config --global user.name "github-actions[bot]"
+          git commit -m "release ${{ steps.retrieve_version.outputs.new_version }}" -m "Release-As: ${{ steps.retrieve_version.outputs.new_version }}"
+          git push
 
       # Create a release in the repository by using the version from the output file
       - name: Create release
@@ -46,7 +54,7 @@ jobs:
 
       - name: Output information
         run: |
-          echo 'Release Output:'
+          echo 'New version:  ${{ steps.retrieve_version.outputs.new_version }}'
           echo 'release_created: ${{ steps.release.outputs.release_created }}'
           echo 'releases_created: ${{ steps.release.outputs.releases_created }}'
           echo 'tag_name: ${{ steps.release.outputs.tag_name }}'
