chore: update workflow

diff --git a/.github/workflows/publish-tag-changelog-release.yml b/.github/workflows/publish-tag-changelog-release.yml
--- a/.github/workflows/publish-tag-changelog-release.yml
+++ b/.github/workflows/publish-tag-changelog-release.yml
@@ -6,17 +6,16 @@ on:
       - release/*
   workflow_dispatch:
 
-
 permissions:
   contents: write
   pull-requests: write
-  id-token: write  # Add this permission
+  id-token: write
 
 jobs:
   publish-tag-changelog-release:
     runs-on: ubuntu-latest
-    outputs:
-      new_version: ${{ steps.retrieve_version.outputs.new_version }}
+    # outputs:
+    #   new_version: ${{ steps.retrieve_version.outputs.new_version }}
 
     steps:
       - name: Checkout code
@@ -25,48 +24,41 @@ jobs:
           fetch-depth: 0
 
       # Get the version from version.json file and store it in the output file
-      - name: Get version from version.json
-        id: retrieve_version
-        run: |
-          new_version=$(jq -r '.version' version.json)
-          if [ -z "$new_version" ]; then
-            echo "Error: version field is empty or not found in version.json!"
-            exit 1
-          fi
-          echo "new_version=$new_version" >> "$GITHUB_OUTPUT"
+      # - name: Get version from version.json
+      #   id: retrieve_version
+      #   run: |
+      #     new_version=$(jq -r '.version' version.json)
+      #     if [ -z "$new_version" ]; then
+      #       echo "Error: version field is empty or not found in version.json!"
+      #       exit 1
+      #     fi
+      #     echo "new_version=$new_version" >> "$GITHUB_OUTPUT"
 
       # Create a release in the repository by using the version from the output file
       - name: Create release
         id: release
         uses: googleapis/release-please-action@v4
         with:
-          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}  
-          target-branch: ${{ github.ref_name }}  # Use the current branch name
+          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
+          target-branch: ${{ github.ref_name }}
           config-file: .github/workflows/release-please-config.json
-          # optional. customize path to .release-please-manifest.json
           manifest-file: .github/workflows/.release-please-manifest-rc.json
-          # release-type: simple
-          # prerelease: true
-          # label: release
-          # release-as: ${{ steps.retrieve_version.outputs.new_version }}
-
-          # config-file: .github/workflows/release-please-config.json
 
       # Create tag and release manually after changelog is generated
-      # - name: Create tag and release
-      #   if: steps.release.outputs.releases_created
-      #   run: |
-      #     version=${{ steps.retrieve_version.outputs.new_version }}
-          
+      - name: Create tag and release
+        if: steps.release.outputs.releases_created
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |          
           # Create and push tag
-          # git config --global user.email "github-actions[bot]@users.noreply.github.com"
-          # git config --global user.name "github-actions[bot]"
-          # git tag -a "$version" -m "Release version $version"
-          # git push origin "$version"
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+          git config --global user.name "github-actions[bot]"
+          git tag -a "${{ steps.release.outputs.tag_name }}" -m "Release version ${{ steps.release.outputs.tag_name }}"
+          git push origin "${{ steps.release.outputs.tag_name }}"
           
-          # # Create GitHub release using gh cli
-          # gh release create "$version" \
-          #   --title "Release $version" \
-          #   --notes-file CHANGELOG.md
-        # env:
-        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          # Create GitHub release
+          gh release create "${{ steps.release.outputs.tag_name }}" \
+            --title "Release ${{ steps.release.outputs.tag_name }}" \
+            --notes-file CHANGELOG.md \
+            --prerelease=${{ steps.release.outputs.prerelease }} \
+            --target ${{ github.ref_name }}
